#include "watches/homer/homerFace.c"
#include "watches/homer/hourHand.c"
#include "watches/homer/minHand.c"
#include "watches/homer/secHand.c"
#include "watches/homer/eye.c"
#include "images/foot_16px.c"
